# vars: { d2-config: { layout-engine: dagre; sketch: true } }
direction: right

h1: host 1
h2: host 2
h3: host 3

h1 {
  rocd {
    roc-toolkit
  }
  "your\napp" <-> rocd
}
h2 {
  rocd {
    roc-toolkit
  }
  "your\napp" <-> rocd
}
h3 {
  rocd <-> "your\napp"
  rocd {
    roc-toolkit
  }
}

h1.rocd <-> h2.rocd: conf (ZMQ) { style: { stroke: deepskyblue } }
h1.rocd.roc-toolkit <-> h2.rocd.roc-toolkit: streams (RTP) { style.animated: true }

h2.rocd <-> h3.rocd: conf (ZMQ) { style: { stroke: deepskyblue } }
h2.rocd.roc-toolkit <-> h3.rocd.roc-toolkit: streams (RTP) { style.animated: true }

h3.rocd <-> h1.rocd: conf (ZMQ) { style: { stroke: deepskyblue } }
h3.rocd.roc-toolkit <-> h1.rocd.roc-toolkit: streams (RTP) { style.animated: true }
