site_name: rocd documentation
copyright: Copyright (c) Roc Streaming authors.

repo_url: https://github.com/roc-streaming/rocd
edit_uri: https://github.com/roc-streaming/rocd/edit/main/docs/

theme:
  name: material
  features:
    - navigation.sections
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.extra # definition lists, ...
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  # see https://landmaj.github.io/mkdocs-d2-plugin/guide/configuration/
  - d2:
      scale: 0.8    # default was too large
      pad: 5        # image padding (all 4 sides)
      layout: dagre # https://d2lang.com/tour/layouts
      #layout: elk
      theme: 3      # https://d2lang.com/tour/themes
      #sketch: True  # fancy lines
      dark_theme: 200
      # TODO: https://d2lang.com/tour/layouts#directions-per-container-tala-only
  - search
  # FIXME: problem with perms; see Makefile
  #- plantuml:
  #    puml_keyword: plantuml
  #    puml_url: https://www.plantuml.com/plantuml/
  #    request_timeout: 500
  #    interaction:
  #      enabled: false # disable controls: zoom, moving, ...
  #- build_plantuml: # other PlantUML plugin; not used; see shell.nix
  #    render: local

extra_css:
  - stylesheets/extra.css

nav:
  - Overview: index.md
  - Implementation:
      - Architecture: implementation/architecture.md
      - P2P protocol: implementation/p2p_protocol.md
      - Use of Roc Toolkit: implementation/roc_toolkit.md
      - Relation to Roc Cast: implementation/roc_cast.md
  - Glossary: glossary.md
  - Roadmap: roadmap.md
