name: "build"

on:
  push:
    branches:
      - main
    tags:
      - v*

  pull_request:

  repository_dispatch:
    types:
      - trigger_build

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # user build (using cargo install)
  linux-user:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: default
            flags: --features=
            libs:

          - name: pipewire
            flags: --features=pipewire
            libs: libpipewire-0.3-dev libspa-0.2-dev

    name: linux-user/${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install libs
        uses: roc-streaming/ci/actions/install-packages@main
        with:
          packages: ${{ matrix.libs }}

      - name: Cargo install
        run: |
          cargo install --path . ${{ matrix.flags }}

      - name: Run help
        run: |
          rocd --help

  # developer build (using pixi and task)
  linux-dev:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: default
            flags:
            libs: pipewire libpipewire-0.3-dev libspa-0.2-dev
            init: systemctl --user start pipewire

          - name: pipewire
            flags: features=driver-tests,pipewire
            libs: pipewire libpipewire-0.3-dev libspa-0.2-dev
            init: systemctl --user start pipewire

          - name: minimal
            flags: features=
            libs:

    name: linux-dev/${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install pixi
        uses: roc-streaming/ci/actions/install-pixi@main

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install libs
        uses: roc-streaming/ci/actions/install-packages@main
        with:
          packages: ${{ matrix.libs }}

      - name: Run init
        run: |
          ${{ matrix.init }}

      - name: Dev profile
        run: |
          pixi run task profile=dev ${{ matrix.flags }}

      - name: Release profile
        run: |
          pixi run task profile=release ${{ matrix.flags }}

  # documentation build (using pixi and task)
  linux-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install pixi
        uses: roc-streaming/ci/actions/install-pixi@main

      - name: Build docs
        run: |
          pixi run task docs
